spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_scheduler
    username: scheduler
    password: scheduler
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
